# coding: utf-8

# Twitter
ENV['TWITTER_KEY'] = "YOUR_CONSUMER_KEY"
ENV['TWITTER_SECRET'] = "YOUR_CONSUMER_SECRET"

# GitHub
#ENV['GITHUB_CLIENT_ID'] = "YOUR_CLIENT_ID"
#ENV['GITHUB_SECRET'] = "YOUR_SECRET"

# Facebook
#ENV['FACEBOOK_APP_ID'] = "YOUR_APP_ID"
#ENV['FACEBOOK_APP_SECRET'] = "YOUR_APP_SECRET"
